=begin pod

=head1 NAME

App::Moneymoor::Util::Period - budget periods: monthly-with-anchor-day
and every-N-weeks pay windows.

=head1 SYNOPSIS

=begin code :lang<raku>

use App::Moneymoor::Util::Period;

# The default scheme is the calendar month, which is what every
# budget written before periods existed was already doing.
my $cal = App::Moneymoor::Util::Period.default-scheme;
say $cal.period-of('2026-08-19');      # 2026-08-01
say $cal.label('2026-08-01');          # August 2026

# Paid on the 14th: the period runs 14th to 13th.
my $pay = App::Moneymoor::Util::Period.monthly(anchor-day => 14);
say $pay.period-of('2026-08-13');      # 2026-07-14
say $pay.period-of('2026-08-14');      # 2026-08-14   (the anchor day
                                       #  belongs to the period it
                                       #  starts)
say $pay.next-period('2026-08-14');    # 2026-09-14
say $pay.label('2026-08-14');          # 14 Aug – 13 Sep 2026

# Anchored on the 31st: short months clamp, and the chain recovers.
my $eom = App::Moneymoor::Util::Period.monthly(anchor-day => 31);
say $eom.next-period('2026-01-31');    # 2026-02-28
say $eom.next-period('2026-02-28');    # 2026-03-31   (not 03-28)
say $eom.prev-period('2026-02-28');    # 2026-01-31
say $eom.next-period('2028-01-31');    # 2028-02-29   (leap year)

# Paid every four weeks from a first payday. No month ever lines up
# with this, which is exactly why it exists.
my $four = App::Moneymoor::Util::Period.weekly(
    weeks => 4, anchor => '2026-08-14');
say $four.period-of('2026-09-12');     # 2026-09-11
say $four.period-of('1999-01-01');     # 1998-12-11   (years before
                                       #  the anchor is fine: k is
                                       #  negative)
say $four.label('2026-08-14');         # 14 Aug – 10 Sep 2026

# The sequence the engine iterates.
say $pay.periods-through('2026-08-14', '2026-11-14').join(' ');
# 2026-08-14 2026-09-14 2026-10-14 2026-11-14

# The serialisation the budget file stores.
say $four.to-hash;      # {anchor => 2026-08-14, type => weekly,
                        #  weeks => 4}
my $same = App::Moneymoor::Util::Period.from-hash($four.to-hash);

# The scheme itself, in words, for a settings line or a toast.
say $cal.describe;      # Calendar month
say $pay.describe;      # Monthly from the 14th
say $four.describe;     # Every 4 weeks from 14 Aug 2026

=end code

=head1 DESCRIPTION

People do not budget in calendar months. They budget from one payday
to the next: the money that arrived on the 14th has to reach the 13th,
and someone paid every four weeks has a window that lines up with no
month at all. Moneymoor's engine therefore buckets by B<budget
period>, and this module is the only thing in the app that knows what
a period is.

It is pure: no DB, no I/O, no state. An instance holds one scheme and
answers questions about it.

=head2 THE TWO SCHEMES

=item B<monthly> with an C<anchor-day> of 1–31. C<anchor-day == 1> is
      the calendar month exactly, and is the default — a budget that
      never touches this setting behaves as it always did. C<14> gives
      14th → 13th.
=item B<weekly> with C<weeks> ≥ 1 and an C<anchor> date, the user's
      first payday. Starts fall on C<anchor + k·7·weeks> days for
      B<every> integer C<k>, negative included, so a transaction dated
      years before the anchor still buckets — a budget file whose
      owner sets their scheme up today and then imports last year's
      statements must not fall off the front of the sequence.

=head2 IDENTITY IS THE START DATE

A period is named by its own start, as a C<'YYYY-MM-DD'> string. That
is the whole identity: there is no period id, no ordinal, no
month-plus-index pair.

Two consequences the rest of the engine leans on:

=item B<Lexicographic order is chronological order.> Zero-padded ISO
      dates sort as text exactly as they sort as dates, so the
      derivation can C<le> / C<gt> period keys, C<sort> them, use them
      as C<Hash> keys and compare a viewed period against a
      C<through-period> without parsing anything.
=item B<The calendar month degenerates into the general case.> Under
      C<monthly/1> every period is C<'YYYY-MM-01'>, so the old
      C<'YYYY-MM'> keys migrate by appending C<'-01'> and nothing else
      about the algebra changes.

=head2 CLAMP, NEVER ADD DAYS

The monthly sequence is generated by iterating B<months> and clamping
the anchor day into each one — never by adding a day count. Under
C<< anchor-day => 31 >>:

=begin code :lang<raku>
2026-01-31 → 2026-02-28 → 2026-03-31 → 2026-04-30 → 2026-05-31
2028-01-31 → 2028-02-29 → 2028-03-31
=end code

February clamps to the 28th (29th in a leap year), and then March goes
straight back to the 31st. Anything built on "add 31 days", or on
stepping from the clamped date, drifts: 2026-02-28 plus a month is
2026-03-28, and by December the budget's periods have walked three
days away from the user's payday. The clamp is applied to the
B<anchor>, and the anchor is a property of the scheme, so the sequence
cannot drift no matter how many short months it crosses.

Every calendar month contains exactly one monthly period start, for
every anchor day.

=head2 DIE, OR RETURN THE EMPTY STRING

The split is deliberate:

=item The B<constructors and the navigation methods> — C<monthly>,
      C<weekly>, C<from-hash>, C<period-of>, C<next-period>,
      C<prev-period>, C<periods-through> — B<throw>. They are called
      from the engine and the gateways, whose inputs have already been
      validated; an C<anchor-day> of 32, or a C<next-period> of a
      string that is not a period start under this scheme, means a
      caller's key has drifted. Continuing from that quietly produces
      a budget bucketed two ways at once, which surfaces days later as
      money that does not add up. C<next-period> and C<prev-period>
      therefore insist that their argument satisfies
      C<period-of($p) eq $p>, and say so loudly when it does not.
=item C<label> B<returns C<''>>. Labels are composed inside
      C<Selkie::Store> selectors, where an exception takes out the
      whole subscription walk, and the frames between construction and
      C<app/init> genuinely have no period yet. Same reasoning as the
      UI's old C<month-label>, which this method replaced.

=head2 LABELS

C<monthly/1> keeps the label the app already showed:
C<'2026-08-01'> → C<"August 2026">. Every other scheme labels the
range, start to end, where the end is the next period's start minus a
day:

=begin code :lang<raku>
monthly/14, 2026-08-14      # 14 Aug – 13 Sep 2026
monthly/14, 2026-12-14      # 14 Dec 2026 – 13 Jan 2027
monthly/31, 2026-02-28      # 28 Feb – 30 Mar 2026
weekly/2,   2026-08-14      # 14 – 27 Aug 2026
=end code

A repeated month is written once, a repeated year is written once, and
a range that crosses a year boundary carries the year on both sides.
The separator is an en dash with spaces around it, and the day numbers
are not zero-padded — this is a banner line, not a key.

The month names are a module-local English table rather than anything
locale-derived, for the same reason the old C<month-label>'s were: a label
whose text depends on the machine's locale makes every layout pin in
the test suite depend on the machine's locale.

=head2 DESCRIBING THE SCHEME, NOT A PERIOD

C<label> names one period; C<describe> names the B<scheme>. They are
different questions and the answers share nothing: "14 Aug – 13 Sep
2026" tells you which window you are looking at, and "Monthly from the
14th" tells you how every window is cut. The settings line that says
what a budget is on, the picker that opens preselected on it, and the
toast that confirms a change all want the second one:

=begin code :lang<raku>
monthly/1                     # Calendar month
monthly/14                    # Monthly from the 14th
monthly/3                     # Monthly from the 3rd
monthly/31                    # Monthly from the 31st
weekly/1  from 2026-08-14     # Every week from 14 Aug 2026
weekly/4  from 2026-08-14     # Every 4 weeks from 14 Aug 2026
=end code

The ordinal suffix is the real English rule, teens included — the 11th,
12th and 13th take C<th> where the 1st, 2nd and 3rd take C<st>, C<nd>
and C<rd> — because an anchor day is a number the user typed and
"Monthly from the 11st" reads as a bug in everything else too. The
weekly date is written in C<label>'s style (abbreviated month, no
zero-padded day) so the two never look like they came from different
apps, and the singular case drops the count: "Every week", not "Every
1 weeks".

=head1 METHODS

=head2 Construction

=item C<Period.monthly(Int:D :$anchor-day = 1)> — throws unless
      1 ≤ C<$anchor-day> ≤ 31.
=item C<Period.weekly(Int:D :$weeks!, :$anchor!)> — C<$anchor> is a
      C<Date> or a C<'YYYY-MM-DD'> C<Str>. Throws unless
      C<$weeks> ≥ 1 and the anchor is a real date.
=item C<Period.default-scheme> — C<monthly/1>, the calendar month.
=item C<Period.from-hash(%h)> / C<< .to-hash(--> Hash) >> — the
      serialisation seam. The shapes, with the C<snake_case> keys the
      budget file stores as JSON, are
      C<< {type => 'monthly', anchor_day => 14} >> and
      C<< {type => 'weekly', weeks => 4, anchor => '2026-08-14'} >>.
      C<from-hash> throws on an unknown type, a missing field or a
      value out of range; it accepts a C<Str> where an C<Int> belongs
      (a JSON round-trip through a text column is entitled to
      stringify a number) but validates it either way, and it ignores
      keys it does not know so that a file written by a later version
      still opens. C<from-hash(.to-hash)> reproduces the scheme
      exactly.
=item C<.new> — B<throws>. There is no shape of C<Period> that is not
      one of the two schemes, so the only way in is a named
      constructor.

=head2 Accessors

=item C<< .type(--> Str) >> — C<'monthly'> or C<'weekly'>.
=item C<< .anchor-day(--> Int) >> — monthly only; C<Int> type object
      on a weekly scheme.
=item C<< .weeks(--> Int) >> / C<< .anchor(--> Date) >> — weekly only.

=head2 The sequence

=item C<< .period-of($date --> Str) >> — the start of the period
      containing C<$date>, which may be a C<Date> or a
      C<'YYYY-MM-DD'> C<Str>. Throws on a malformed date.
=item C<< .next-period(Str:D $period --> Str) >> /
      C<< .prev-period(Str:D $period --> Str) >> — one step along the
      sequence. Throw unless C<$period> is a period start under this
      scheme.
=item C<< .periods-through(Str:D $from, Str:D $through --> List) >> —
      the inclusive, contiguous run of starts from C<$from> to
      C<$through>. Throws unless both are period starts and
      C<$from> ≤ C<$through>. This is what the derivation iterates.
=item C<< .label(Str $period --> Str) >> — the human label, or C<''>.

=head2 The scheme in words

=item C<< .describe(--> Str) >> — the scheme itself, in a phrase fit
      for a settings line, a picker or a toast: C<'Calendar month'>,
      C<'Monthly from the 14th'>, C<'Every 4 weeks from 14 Aug 2026'>.
      Takes no period and cannot fail — see DESCRIBING THE SCHEME, NOT
      A PERIOD.

=head1 SEE ALSO

=item L<App::Moneymoor::Service::Budget> — the derivation, which keys
      every assignment, every bucketed transaction and every rollover
      chain by the strings this module produces.
=item L<App::Moneymoor::Screen::Main::Subscriptions> — composes the
      banner whose labels C<label> now supplies; its old
      C<month-label> is the sub C<label>'s C<monthly/1> output
      reproduces exactly.
=item L<App::Moneymoor::Util::Money> — the other pure engine-tier
      utility.

=end pod

unit class App::Moneymoor::Util::Period;

#| Full month names, indexed from 1, for the C<monthly/1> label. An
#| English table rather than anything locale-derived: see the LABELS
#| section — a locale-dependent name would make every layout pin in
#| the test suite depend on the machine running it.
my constant MONTH-NAMES = (
    'January', 'February', 'March',     'April',   'May',      'June',
    'July',    'August',   'September', 'October', 'November', 'December',
);

#| The same table abbreviated, for range labels. Three characters
#| each, so a two-sided label fits a narrow banner.
my constant MONTH-ABBR = (
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
);

#| En dash with spaces, the range separator in every label that has
#| two sides.
my constant RANGE-DASH = ' – ';

my constant MONTHLY = 'monthly';
my constant WEEKLY  = 'weekly';

has Str  $.type;         #= 'monthly' or 'weekly'
has Int  $.anchor-day;   #= monthly only: 1..31, clamped into short months
has Int  $.weeks;        #= weekly only: >= 1
has Date $.anchor;       #= weekly only: the first payday

# --- input coercion -------------------------------------------------

#|( A C<Date> or a C<'YYYY-MM-DD'> C<Str> in, a C<Date> out.

    The shape is checked before C<Date.new> so that the message names
    the caller's value and what was expected, rather than leaking
    Rakudo's own wording, and so that C<'2026-8-4'> — which C<Date>
    rejects — is rejected here for the same reason as C<'2026-02-30'>:
    period keys are canonical or they are not keys. )
my sub as-date($value, Str:D $what --> Date) {
    return $value if $value ~~ Date:D;
    die "Malformed $what '{ ($value // '(undefined)').gist }' "
            ~ "(expected a Date or a 'YYYY-MM-DD' string)"
        unless $value ~~ Str:D
            && $value ~~ / ^ \d ** 4 '-' \d ** 2 '-' \d ** 2 $ /;
    my $date = try Date.new($value);
    die "Malformed $what '$value' (no such date)" without $date;
    $date;
}

#|( A serialised numeric field in, an C<Int> out.

    C<Str> is accepted because a JSON round-trip through a text column
    is entitled to hand back C<'14'>, and a whole C<Real> because a
    JSON writer is entitled to hand back C<14.0>. C<Bool> is refused
    explicitly: C<True ~~ Int> is C<True> in Raku, so an
    C<< anchor_day => True >> would otherwise sail through as day 1. )
my sub as-int($value, Str:D $field --> Int) {
    die "Field '$field' must be a whole number "
            ~ "(got { ($value // '(missing)').gist })"
        if $value ~~ Bool;
    return $value.Int if $value ~~ Real:D && $value == $value.floor;
    return $value.trim.Int
        if $value ~~ Str:D && $value.trim ~~ / ^ '-'? \d+ $ /;
    die "Field '$field' must be a whole number "
        ~ "(got { ($value // '(missing)').gist })";
}

# --- construction ---------------------------------------------------

#|( There is no valid C<Period> that is not one of the two schemes,
    and C<.new> with no arguments would build one with a C<type> of
    C<Str> that every method would then have to defend against.
    Closing the door is cheaper than defending it. )
method new(|) {
    die "App::Moneymoor::Util::Period has no public .new — build a "
        ~ "scheme with .monthly, .weekly, .default-scheme or "
        ~ ".from-hash";
}

#|( The calendar-month family. C<$anchor-day> is the day of the month
    the user is paid; it is clamped into months that are too short to
    contain it (see CLAMP, NEVER ADD DAYS), so 29, 30 and 31 are all
    legal and all mean "the last of these days that the month has".

    Throws rather than fails on an out-of-range day: every caller —
    the budget-creation flow, the Settings dialog, C<from-hash> — has
    validated its input already, and a scheme silently substituted for
    the one asked for re-buckets somebody's money. )
method monthly(Int:D :$anchor-day = 1) {
    die "anchor-day must be 1..31 (got $anchor-day)"
        unless 1 <= $anchor-day <= 31;
    self.bless(type => MONTHLY, :$anchor-day);
}

#|( The every-N-weeks family. C<$anchor> is the user's first payday —
    any payday, in fact: the sequence extends infinitely in both
    directions from it, so which one they name changes nothing except
    the arithmetic's origin. )
method weekly(Int:D :$weeks!, :$anchor!) {
    die "weeks must be at least 1 (got $weeks)" unless $weeks >= 1;
    my Date $date = as-date($anchor, 'anchor');
    self.bless(type => WEEKLY, :$weeks, anchor => $date);
}

#| The scheme a budget has until somebody chooses otherwise: the
#| calendar month, identical in every respect to what the engine did
#| before periods existed.
method default-scheme { self.monthly(anchor-day => 1) }

#| The scheme as the budget file stores it — C<snake_case> keys, a
#| C<'YYYY-MM-DD'> string for the anchor, JSON-ready as it stands.
method to-hash(--> Hash) {
    $!type eq MONTHLY
        ?? { type => MONTHLY, anchor_day => $!anchor-day }
        !! { type => WEEKLY, weeks => $!weeks, anchor => $!anchor.Str };
}

#|( C<to-hash>'s inverse, and the reader for whatever the budget file
    holds.

    Strict about the fields it knows and silent about the ones it does
    not: an unknown key is a file written by a later version, which
    should still open, while a missing or out-of-range known field is
    a file that cannot be honoured and must not be guessed at. )
method from-hash($hash) {
    die "Period scheme must be a hash (got { ($hash // '(undefined)').gist })"
        unless $hash ~~ Associative:D;
    my %h = $hash.Hash;

    my $type = %h<type>;
    die "Period scheme is missing its 'type'" unless %h<type>:exists;
    die "Period scheme 'type' must be a string "
            ~ "(got { ($type // '(undefined)').gist })"
        unless $type ~~ Str:D;

    given $type {
        when MONTHLY {
            die "Monthly period scheme is missing 'anchor_day'"
                unless %h<anchor_day>:exists;
            self.monthly(anchor-day => as-int(%h<anchor_day>, 'anchor_day'));
        }
        when WEEKLY {
            die "Weekly period scheme is missing 'weeks'"
                unless %h<weeks>:exists;
            die "Weekly period scheme is missing 'anchor'"
                unless %h<anchor>:exists;
            self.weekly(weeks  => as-int(%h<weeks>, 'weeks'),
                        anchor => %h<anchor>);
        }
        default {
            die "Unknown period scheme type '$type' "
                ~ "(expected '{ MONTHLY }' or '{ WEEKLY }')";
        }
    }
}

#| Short enough for a test failure or a warning to name the scheme
#| that produced it: C<Period(monthly/14)>, C<Period(weekly/4 from
#| 2026-08-14)>.
method gist(--> Str) {
    $!type eq MONTHLY
        ?? "Period(monthly/{ $!anchor-day })"
        !! "Period(weekly/{ $!weeks } from { $!anchor })";
}

# --- the sequence, in Dates -----------------------------------------
#
# Everything public is a thin wrapper over these three. They take and
# return `Date`s, so the string form is produced exactly once, at the
# boundary, and no internal step ever re-parses a key it just wrote.

#|( The anchor day placed inside one specific month, shortened to the
    month's last day where it has to be. This is the clamp, and it is
    the only place a monthly start is ever built. )
my sub clamp-anchor(Int:D $year, Int:D $month, Int:D $day --> Date) {
    my Date $first = Date.new($year, $month, 1);
    Date.new($year, $month, min($day, $first.days-in-month));
}

#| The month before / after (year, month), as a two-element list.
my sub shift-month(Int:D $year, Int:D $month, Int:D $by --> List) {
    my Int $m = $month + $by;
    my Int $y = $year;
    while $m > 12 { $m -= 12; $y++ }
    while $m < 1  { $m += 12; $y-- }
    ($y, $m);
}

#| The start of the period containing C<$date>.
method !start-of(Date:D $date --> Date) {
    if $!type eq MONTHLY {
        # Clamp into the date's own month; if the date falls before
        # that, it belongs to the month before's period. Two clamps at
        # most, and never a day count.
        my Date $start = clamp-anchor($date.year, $date.month, $!anchor-day);
        return $start unless $date < $start;
        my ($y, $m) = shift-month($date.year, $date.month, -1);
        return clamp-anchor($y, $m, $!anchor-day);
    }
    # `div` on Int floors towards -Inf, which is what makes dates
    # before the anchor land on the right side: (-1) div 14 is -1, not
    # 0, so the day before the anchor is in the period that ends on
    # it.
    my Int $k = ($date - $!anchor) div (7 * $!weeks);
    $!anchor + $k * 7 * $!weeks;
}

#| The next start after the start C<$start>. Assumes C<$start> is one.
method !next-start(Date:D $start --> Date) {
    return $start + 7 * $!weeks unless $!type eq MONTHLY;
    my ($y, $m) = shift-month($start.year, $start.month, 1);
    clamp-anchor($y, $m, $!anchor-day);
}

#| The start before the start C<$start>. Assumes C<$start> is one.
method !prev-start(Date:D $start --> Date) {
    return $start - 7 * $!weeks unless $!type eq MONTHLY;
    my ($y, $m) = shift-month($start.year, $start.month, -1);
    clamp-anchor($y, $m, $!anchor-day);
}

# --- the public sequence --------------------------------------------

method period-of($date --> Str) {
    self!start-of(as-date($date, 'date')).Str;
}

#|( A period key in, its neighbour out.

    C<$period> must be a real start under this scheme. A key that is
    not one came from somewhere that bucketed with different rules —
    a stale scheme, a hand-edited row, a C<'YYYY-MM'> month that never
    got the migration — and stepping from it produces a second,
    parallel set of keys that the derivation will happily sum
    alongside the real ones. )
method !check-start(Str:D $period, Str:D $what --> Date) {
    my Date $date = as-date($period, $what);
    my Date $start = self!start-of($date);
    die "'$period' is not a period start under { self.gist } "
            ~ "(its period starts { $start })"
        unless $start == $date;
    $start;
}

method next-period(Str:D $period --> Str) {
    self!next-start(self!check-start($period, 'period')).Str;
}

method prev-period(Str:D $period --> Str) {
    self!prev-start(self!check-start($period, 'period')).Str;
}

#|( Every start from C<$from> through C<$through>, inclusive and
    contiguous — the run the derivation walks.

    Both ends must be starts: a range whose endpoints are not on the
    sequence has no unambiguous meaning, and quietly rounding them
    would hand the engine a first bucket that is not the one the
    caller named. )
method periods-through(Str:D $from, Str:D $through --> List) {
    my Date $start = self!check-start($from, 'from period');
    my Date $end   = self!check-start($through, 'through period');
    die "'$from' is after '$through'" if $start > $end;

    my Str @periods;
    my Date $cursor = $start;
    while $cursor <= $end {
        @periods.push($cursor.Str);
        $cursor = self!next-start($cursor);
    }
    @periods.List;
}

# --- labels ---------------------------------------------------------

#|( The human label for a period, for the banner and pane titles, or
    C<''> for anything that is not a period start under this scheme —
    including C<Str> type objects and the empty string.

    Never throws: the label is composed inside a store selector, where
    an exception takes out the subscription walk, and there are frames
    early in startup with no period to name yet. Every I<other> method
    here throws on the same input, which is the difference between a
    key (a fact the engine must not guess at) and a caption. )
method label(Str $period --> Str) {
    return '' without $period;
    my $date = try as-date($period, 'period');
    return '' without $date;
    my Date $start = self!start-of($date);
    return '' unless $start == $date;

    if $!type eq MONTHLY && $!anchor-day == 1 {
        return MONTH-NAMES[$start.month - 1] ~ ' ' ~ $start.year.fmt('%04d');
    }

    # The period's last day: the day before the next one starts. The
    # end is derived, never stored — under a clamping scheme it is not
    # a fixed number of days away from the start.
    my Date $end = self!next-start($start) - 1;

    my Str $sy = $start.year.fmt('%04d');
    my Str $ey = $end.year.fmt('%04d');
    my Str $sm = MONTH-ABBR[$start.month - 1];
    my Str $em = MONTH-ABBR[$end.month - 1];

    return "{ $start.day } $sm $sy" ~ RANGE-DASH ~ "{ $end.day } $em $ey"
        unless $sy eq $ey;
    return "{ $start.day } $sm" ~ RANGE-DASH ~ "{ $end.day } $em $ey"
        unless $sm eq $em;
    "{ $start.day }" ~ RANGE-DASH ~ "{ $end.day } $em $ey";
}

# --- the scheme in words --------------------------------------------

#|( C<$n> with its English ordinal suffix: 1st, 2nd, 3rd, 4th … 11th,
    12th, 13th … 21st, 22nd, 23rd … 31st.

    The teens are the whole reason this is a routine rather than an
    index into a three-element table: 11, 12 and 13 take C<th> despite
    ending in 1, 2 and 3, and an anchor day is a number the user typed,
    so "the 11st" would be on screen the moment somebody is paid on the
    11th. Written for the general case rather than for 1..31, because a
    rule that is right only inside its caller's range is a rule that
    breaks when the caller moves. )
my sub ordinal(Int:D $n --> Str) {
    my Int $teens = $n.abs % 100;
    return "{ $n }th" if 11 <= $teens <= 13;
    given $n.abs % 10 {
        when 1  { "{ $n }st" }
        when 2  { "{ $n }nd" }
        when 3  { "{ $n }rd" }
        default { "{ $n }th" }
    }
}

#|( The scheme itself in words — not a period; C<label> does that.

    What the Settings dialog's period line reads, what the picker
    preselects against, and what the toast that confirms a change
    names. Cannot fail and takes no argument: a scheme is always one of
    the two shapes, both fully described by their own fields. )
method describe(--> Str) {
    if $!type eq MONTHLY {
        # monthly/1 is the calendar month, and calling it "Monthly from
        # the 1st" would describe the default — the thing most budgets
        # are on — in the vocabulary of the exception.
        return 'Calendar month' if $!anchor-day == 1;
        return 'Monthly from the ' ~ ordinal($!anchor-day);
    }

    # `label`'s date style, deliberately: the two strings sit inches
    # apart in the Settings dialog and the banner.
    my Str $from = "{ $!anchor.day } { MONTH-ABBR[$!anchor.month - 1] } "
                   ~ $!anchor.year.fmt('%04d');
    $!weeks == 1
        ?? "Every week from $from"
        !! "Every { $!weeks } weeks from $from";
}
